# Generated by Django 3.1.2 on 2020-10-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
